/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Panos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jButtonSolo1 = new javax.swing.JButton();
        jButtonHungarian = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTopMouseClicked(evt);
            }
        });
        jPanelTop.setLayout(null);

        jButtonSolo1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSolo1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSolo1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSolo1.setText("SOLO 1");
        jButtonSolo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSolo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolo1ActionPerformed(evt);
            }
        });
        jPanelTop.add(jButtonSolo1);
        jButtonSolo1.setBounds(50, 240, 308, 25);

        jButtonHungarian.setBackground(new java.awt.Color(0, 0, 0));
        jButtonHungarian.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonHungarian.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHungarian.setText("HUNGARIAN");
        jButtonHungarian.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonHungarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHungarianActionPerformed(evt);
            }
        });
        jPanelTop.add(jButtonHungarian);
        jButtonHungarian.setBounds(50, 270, 308, 25);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("jButton3");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelTop.add(jButton3);
        jButton3.setBounds(50, 300, 308, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/dominoes.jpg"))); // NOI18N
        jPanelTop.add(jLabel1);
        jLabel1.setBounds(-150, 0, 540, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSolo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolo1ActionPerformed
       // new Solo1_Frame().setVisible(true);
        Solo1_Frame sl1=new Solo1_Frame();
        sl1.playGame();
        sl1.setVisible(true);
        setVisible(false);
                
        
    }//GEN-LAST:event_jButtonSolo1ActionPerformed

    private void jPanelTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMouseClicked
        
    }//GEN-LAST:event_jPanelTopMouseClicked

    private void jButtonHungarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHungarianActionPerformed
        Ouggriko_Frame ouggriko=new Ouggriko_Frame();
        ouggriko.setVisible(true);
        ouggriko.playGame();
        setVisible(false);
    }//GEN-LAST:event_jButtonHungarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menu().setVisible(true);
                
               
        

            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonHungarian;
    private javax.swing.JButton jButtonSolo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelTop;
    // End of variables declaration//GEN-END:variables
}
